### ISSUE TITLE
Merge in useful design info from diego-dev-notes ?

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/diego-design-notes#34]
I recently ran into https://github.com/cloudfoundry/diego-dev-notes which seems to contain quite detailed and useful information.

Wouldn't it make sense to merge part of diego-dev-notes into diego-design-notes ?

**Comment by ematpl** [comment]
Hi, @gberche-orange,

Thanks for the suggestion! I think in general it makes sense to merge the two notes repos, probably renaming 'diego-design-notes' to 'diego-notes' in the process. The 'diego-dev-notes' repo at one point had been private as an internal discussion space for the Diego team, but now that it's public there's no reason to keep them separate. I've made https://www.pivotaltracker.com/story/show/124971441 in the Diego tracker to capture that idea, but it's a fairly low priority to do, so I can't give you a strong estimate on when it will get done. I'll close out this issue now, though, since we have that separate story to track the work.

Thanks again,
Eric

**Comment by gberche-orange** [comment]
great, thanks a lot @ematpl
